### ISSUE TITLE
How to clear the previous Entry?

### ISSUE THREAD

**Issue by ezechinwa** [IrvingRyan/VerifyCodeView#3]
Hi, Assume the user makes an error how do i clear the numbers.

**Comment by IrvingRyan** [comment]
@ezechinwa do you have any device information?

**Comment by mty19901218** [comment]
you can solve the issue by change and add code following :
 @Override
    public InputConnection onCreateInputConnection(EditorInfo outAttrs) {
        //define keyboard to number keyboard
        MyInputConnection fic = new MyInputConnection(this, false);
        outAttrs.actionLabel = null;
        outAttrs.inputType = InputType.TYPE_CLASS_NUMBER;
        outAttrs.imeOptions = EditorInfo.IME_ACTION_NEXT;
        return fic;
    }

public class MyInputConnection extends BaseInputConnection{
        public MyInputConnection(View targetView, boolean fullEditor) {
            super(targetView, fullEditor);
        }
        @Override
        public boolean sendKeyEvent(KeyEvent event) {
            return super.sendKeyEvent(event);
        }

        @Override
        public boolean deleteSurroundingText(int beforeLength, int afterLength) {
            return sendKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DEL))&&sendKeyEvent(new KeyEvent(KeyEvent.ACTION_UP,KeyEvent.KEYCODE_DEL));
//            return super.deleteSurroundingText(beforeLength, afterLength);
        }
    }

**Comment by ezechinwa** [comment]
Cheers will check it out now.

**Comment by IrvingRyan** [comment]
@mty19901218 thanks, i totally forget the phone which have physical buttons.

**Comment by IrvingRyan** [comment]
@ezechinwa code changed.see the commit [https://github.com/IrvingRyan/VerifyCodeView/commit/0384bc924b94be4526f4df01f604314b35232fa2](https://github.com/IrvingRyan/VerifyCodeView/commit/0384bc924b94be4526f4df01f604314b35232fa2)
